### ISSUE TITLE
psr-4 autloading not working on iis server

### ISSUE THREAD

**Issue by Arti-sys** [docusign/code-examples-php#12]
I am trying to run this code on IIS server but not working it shows me 
 Uncaught Error: Class '\Example\Controllers\Examples\eSignature\Home' not found.

I am running PHP 7.3 and IIS 10.0

**Comment by LarryKlugerDS** [comment]
Sorry for the late reply. Have you been able to solve the issue?

Thanks,
Larry

**Comment by AaronWDS** [comment]
I took a look into where you would have been trying to load this: the Home.php Controller would have been in the parent directory, not eSignature. It is possible that you were facing this problem while we were in the process of porting in the rooms examples.  Please git pull the repo to test it again.
