### ISSUE TITLE
Incorrect comment in line 105 of JWTService.php

### ISSUE THREAD

**Issue by fracplatz** [docusign/code-examples-php#13]
The comment says:
Try to get an access token using the authorization code grant.

This was most likely copied from the CodeGrantService.php code and not updated to say JWT.  I was initially very confused as to why you would try to get a code grant token in the JWT service but then realized it was just an incorrect comment.

**Comment by InbarGazit** [comment]
We will fix this.

**Comment by LarryKlugerDS** [comment]
@InbarGazit , please update this isssue with the Jira number. Thank you

**Comment by AaronWDS** [comment]
This comment has been deleed, thanks!
