### ISSUE TITLE
JWT Authetication

### ISSUE THREAD

**Issue by Arti-sys** [docusign/code-examples-php#15]
After JWT Authetication i am not able to call any API in list. It is redirecting to base URL.
Please help..

**Comment by Arti-sys** [comment]
Like Create Envelope API

**Comment by AaronWDS** [comment]
We've made some updates to the launcher since this was posted. Please git pull to see the latest changes, update the config, use `composer update` to point to the latest sdk and dependencies, then try it again.  Please open a new issue if you encounter anything else.
