### ISSUE TITLE
EnvelopeTemplate modele definition bug

### ISSUE THREAD

**Issue by DylanGD** [docusign/code-examples-php#16]
Example **EG008CreateTemplate.php** [here](https://github.com/docusign/code-examples-php/blob/master/src/Controllers/Examples/eSignature/EG008CreateTemplate.php)

```
        # Create top two objects
        $envelope_template_definition = new EnvelopeTemplateDefinition([
            'description' => "Example template created via the API",
            'name' => $this->template_name,
            'shared' => "false"
        ]);
        # Top object:
        $template_request = new EnvelopeTemplate([
            'documents' => [$document], 'email_subject' => "Please sign this document",
            'envelope_template_definition' => $envelope_template_definition,
            'recipients' => new Recipients([
            'signers' => [$signer], 'carbon_copies' => [$cc]]),
            'status' => "created"
        ]);
```

this declaration :

```
   'envelope_template_definition' => $envelope_template_definition,
```

does not match anything in the EnvelopeTemplate model definition => [here](https://github.com/docusign/docusign-php-client/blob/master/src/Model/EnvelopeTemplate.php) so it does not work...

Can you check the mistake please, thanks!

**Comment by ivdinkovds** [comment]
Thank you for reporting this issue to us. EnvelopeTemplate does not contain **envelope_template_definition**. "description", "name" and "shared" are properties of EnvelopeTemplate

**Comment by ivdinkovds** [comment]
@DylanGD fix deployed
