### ISSUE TITLE
Possibly incorrect `ds_expiration` persisted to $_SESSION by JWTService?

### ISSUE THREAD

**Issue by AlbinoDrought** [docusign/code-examples-php#18]
In [JWTService](./src/Services/JWTService.php), `$_SESSION['ds_expiration']` [is set like this](https://github.com/docusign/code-examples-php/blob/7cc82108271e3faa5faba71f7550278ccbd8eb32/src/Services/JWTService.php#L90):

```php
$_SESSION['ds_expiration'] = time() + (self::$access_token->getExpiresIn() * 1000); # expiration time.
```

PHP's `time()` returns the current unix epoch in seconds:

```
>>> time()
=> 1613082946
>>> time()
=> 1613082948
```

OAuthToken's `getExpiresIn()` property appears to be in seconds too:

```
>>> $token = $auth->generateToken();
=> DocuSign\eSign\Client\Auth\OAuthToken {#5236}
>>> $token->getExpiresIn();
=> "3600"
```

The [DocuSign documentation](https://developers.docusign.com/platform/auth/jwt/jwt-get-token/) specifies that `expires_in` is in seconds:

Name | Description
-- | --
expires_in | The number of seconds before the  access token expires. When your access token expires, your application  should generate a new JWT with your credentials and request a new access  token.

If the "3600" value was treated as seconds, it would be 60 minutes and the correct code may be `$_SESSION['ds_expiration'] = time() + self::$access_token->getExpiresIn()`. The current code enacts an expiration time of `60 * 1000` minutes = about 41 days

**Comment by ivdinkovds** [comment]
@AlbinoDrought, thank you for notifying us regarding this issue. For your reference I created case DEVDOCS-4201

**Comment by ivdinkovds** [comment]
Fixed. Closing the case

**Comment by ivdinkovds** [comment]
Fixed. Closing the case
