### ISSUE TITLE
Docker issues

### ISSUE THREAD

**Issue by webfoolery** [docusign/code-examples-php#19]
I'm new to Docker (not to PHP) so apologies if I'm missing something obvious.
Steps:

1. `docker-compose up` [wait for it to complete]
2. Navigate to http://localhost:8080/
3. Error: `Fatal error: require_once(): Failed opening required '/var/www/html/public/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/public/index.php on line 9`
4. I also tried a `docker-compose build` before the `docker-compose up` but that gave the same result.

I was expecting to see the quickstart. Am I doing something wrong?
Any assistance greatly appreciated.

**Comment by AaronWDS** [comment]
Hey there, 

We'll need to install the dependencies in the docker container before navigating to it. Try the following command:
`docker exec -it --user www-data docusign-php-fpm composer install` then navigate to localhost:8080. If you need to update the  dependencies you can run the same command as above but change install to update so it reads `...composer update` instead. Let us know if this helps you resolve the issue.
