### ISSUE TITLE
code example for backend integration

### ISSUE THREAD

**Issue by krisbailey** [docusign/code-examples-php#21]
I'm trying to find a code example for how to authenticate without needing a user to do something in a browser.  I want a backend system to be able to create an envelope with contents using a template and pushing data in via tabs.  All I see is oauth stuff that talks about users and browser and redirects, etc. I don't have a person doing something in a browser, I need this to happen with 100% no user interaction.  Is that possible?

**Comment by AaronWDS** [comment]
Hi @krisbailey. What you're referring to is called JSON web token (JWT) authentication. We show it working from within the web app in this launcher as an option.  There are some considerations - are you intending to have different user accounts to use this application?  If so, JWT authentication requires that consent is granted on the very first run.  

The consent window looks like this:  
![image](https://user-images.githubusercontent.com/52012222/118789537-ba245a00-b849-11eb-8245-79b0f228e654.png)

Once consent has been granted, that account user can authenticate using JWT.  You can avoid asking for consent to all of your users by configuring your integration to utilize an admin privileged user in your account and granting consent that first time.

Here is an article specifying further details regarding [JWT best practices](https://developers.docusign.com/platform/auth/jwt/jwt-best-practice/).

Finally, here is the JWT code implemented in the launcher (note that we're using the [requestJWTUserToken](https://github.com/docusign/code-examples-php/blob/master/src/Services/JWTService.php#L72) method and not the JWTApplication method. 

Note: the [JWTRequestApplicationToken method does not work with the eSignature API](https://stackoverflow.com/a/61128233/2226328), it only works with The DocuSign Admin API and requires Organization consent for first use. 

To specifically address what you're looking for, you can achieve this through [Example 9](https://github.com/docusign/code-examples-php/blob/master/src/Controllers/Examples/eSignature/EG009UseTemplate.php). That example uses the template that was generated in [Example 8](https://github.com/docusign/code-examples-php/blob/master/src/Controllers/Examples/eSignature/EG008CreateTemplate.php) but can be refactored to point to a different templateID or templateName. it will send an envelope of your documents for your enduser to sign and will be pre populated with the information provided. Hope this helps.

**Comment by kalimajayant** [comment]
Thanks, I got it.

I am interested in APPLICATION AUTHORIZATION, Can you tell me what will the
steps be.

I think for that too, we need JWT

  With this,(APPLICATION AUTHORIZATION) ,the user will not need to
authorize it, right.

What am I trying to achieve is, create a program, that send precoded html
templates for signing.  So the user will not be able to sign in with it.

Is that possible with Application Authorization?

My End user of Api is single user. So it looks odd, to provide consent
everytime.

Thanks.

**Comment by krisbailey** [comment]
I do not need anymore help, thanks!
