### ISSUE TITLE
Getting Template controls logic nd UI created in Docusign Admin panel to the Embedded docusign access

### ISSUE THREAD

**Issue by iyyappanpwilco** [docusign/code-examples-php#26]
Hi,

I have added some logics like adding radio button in the Admin template page 
Can we access the logics and UI in the api level using client id and template id

**Comment by AaronWDS** [comment]
It is possible, [yes](https://github.com/docusign/docusign-esign-php-client/blob/4c833689e664fa04fa824e4f5d937e6ac524cfc7/src/Api/TemplatesApi.php#L5509)

```
        $templates_api = $this->clientService->getTemplatesApi();
        $options = new ListTemplatesOptions();
        $options->setSearchText($this->template_name);
        $results = $templates_api->listTemplates($args['account_id'], $options);

```


This snippet comes from [Example 8](https://github.com/docusign/code-examples-php/blob/master/src/Controllers/Examples/eSignature/EG008CreateTemplate.php) and allows you to get a list of one or more templates with the set options on them.

**Comment by iyyappanpwilco** [comment]
Hi Aaron ,Thank you for your reply , after adding the above code i am not getting any control,s from admin panel I have added the signature and date and text field in the Docusign admin panel ,but the signature and date field are not displayed in the api
kindly help me how to get the signature control ,date control from docusign admin template id to api php

**Comment by AaronWDS** [comment]
if you scroll to the [bottom of this page](https://developers.docusign.com/docs/esign-rest-api/reference/templates/templatedocumenttabs/create/), and click schema you'll see the possibilities of different objects that can be set with creating the template you're looking to have filled in by sending the envelope.
