### ISSUE TITLE
Getting Admin template control logics ,signature and radio button to php api

### ISSUE THREAD

**Issue by iyyappanpwilco** [docusign/code-examples-php#27]
Hi,

I have created template in docusign admin panel with two persons and added the signature for the person1 and two signature for the person2 and added the radio buttons for the second person 
I need to access the logic in  example 32 and 33,but i am not able to get using templateid by
   $envelope_definition = new EnvelopeDefinition([
           'status' => "sent",
           'template_id' => '1ecda85e-c502-4d2f-9bb7-e784277e5032'
       ]);
       $envelope_definition->setWorkflow($workflow);
       $envelope_definition->setTemplateRoles([$signer1, $signer2]);

Please help me to achieve

**Comment by AaronWDS** [comment]
what is the current stack trace you get when the call fails? You can also enable account auditing here to see what [specifically fails when attempting to send the envelope](https://appdemo.docusign.com/preferences/general)

**Comment by AaronWDS** [comment]
this seems related to getting ex33 working with a template, closing this to keep things consolidated into one ticket
