### ISSUE TITLE
Radio button and Date signed in unpausing signature flow

### ISSUE THREAD

**Issue by iyyappanpwilco** [docusign/code-examples-php#28]
Hi ,

Can we add the radio button with some logics in the the unpausing the signatue flow with  docusign php
is it possible can we tell me how to do  it in php

**Comment by AaronWDS** [comment]
I believe [example 33](https://github.com/docusign/code-examples-php/blob/master/src/Controllers/Examples/eSignature/EG033UnpauseSignatureWorkflow.php#L83) does this:

To fire this off you would need to have the views code that shows to the user do the validation and injection, beforehand, then when clicking submit on that page, you create a new envelope definition with the updated parameters you wish to use, all within that new envelope definition. That will have all the various options you set behind the scenes with the radio button and/or other user controls uses.  This code is copied directly from example 33 and will need some modifications to work through your example.

```
        $env = new EnvelopeDefinition([
            'workflow' => new Workflow(['workflow_status' => 'in_progress'])
        ]);
        $envelope_api = $this->clientService->getEnvelopeApi();
        $envelope_option = new UpdateOptions();

        # Update resend envelope parameter
        $envelope_option -> setResendEnvelope('true');
        # Step 3 End

        # Step 4 Start
        # Call Envelopes::update API method to unpause signature workflow
        $envelope = $envelope_api->update(
            $args['account_id'],
            $args['pause_envelope_id'],
            $envelope=$env,
            $options=$envelope_option
        );
        $envelope_id = $envelope['envelope_id'];

```
