### ISSUE TITLE
Sending custom field  to the envelope and receiving that custom field in the web hook

### ISSUE THREAD

**Issue by iyyappanpwilco** [docusign/code-examples-php#32]
Hi,

I have added the custom fields in the envelope as
  $custom_field1 = new TextCustomField([
            'field_id' => '10574617715',
            'name' => 'track_text_d',
            'required' => 'false',
            'show' => 'false', # Yes, include in the CoC
            'value' => '1234567']);
            $custom_field2 = new TextCustomField([
                'field_id' => '10574617714',
                'name' => 'track_text',
                'required' => 'false',
                'show' => 'false', # Yes, include in the CoC
                'value' => 'welcome']);
        $custom_fields = new CustomFields([
            'text_custom_fields' => [$custom_field1,$custom_field2]]);
        $envelope_definition->setCustomFields($custom_fields);
        $envelope_definition->setWorkflow($workflow);
        $envelope_definition->setTemplateRoles([$signer1, $signer2]);
can u tell me the how to call the webhook url locally in php script and get the custom variable

**Comment by LarryKlugerDS** [comment]
Please open a case with DocuSign Developer Support:
Submitting a case via https://support.docusign.com/en/contactSupport. If you have a production account, start by logging in with your production email/password (even if you don’t have a support contract). Then submit a case and be sure to include your developer (demo) account id.

If you don't have a production account, you can still get support by filling in the form on that page.

**Comment by InbarGazit** [comment]
Custom fields data can be retrieved via API - see https://github.com/docusign/code-examples-php/blob/master/src/Services/Examples/eSignature/EnvelopeCustomFieldDataService.php for PHP sample code.
