### ISSUE TITLE
Webhook url notification

### ISSUE THREAD

**Issue by iyyappanpwilco** [docusign/code-examples-php#33]
Hi,

We need to configure notification url  for the each envelope in docusign api php

Kindly let us know how to achieve it i have tried as
$envelopeEvents = ['customFields','recipients'];
        $event_data = new ConnectEventData(['format' => 'xml', 'include_data' =>$envelopeEvents]) ;
        $eventNotification = new EventNotification(['event_data' => $event_data ]);
        $eventNotification->setUrl('https://stagingapi.medneon.com/MedNeonServices/econsent/DocusignWebhookI/');
        $eventNotification->setLoggingEnabled('true');
        $eventNotification->setRequireAcknowledgment('true');
        $envelope_definition->setEventNotification($eventNotification);

**Comment by LarryKlugerDS** [comment]
$envelopeEvents and include_data are not right.

Try

````
    $event_data1 = new \DocuSign\eSign\Model\ConnectEventData([
        'format' => "xml" 
        ]);
    $recipient_event1 = new \DocuSign\eSign\Model\RecipientEvent([
        'recipient_event_status_code' => "Sent" 
        ]);
    $recipient_events1 = [$recipient_event1];
    $envelope_event1 = new \DocuSign\eSign\Model\EnvelopeEvent([
        'envelope_event_status_code' => "Completed" 
        ]);
    $envelope_events1 = [$envelope_event1];
    $event_notification1 = new \DocuSign\eSign\Model\EventNotification([
        'envelope_events' => $envelope_events1,  
        'event_data' => $event_data1,  
        'include_envelope_void_reason' => "true",  
        'logging_enabled' => "true",  
        'recipient_events' => $recipient_events1,  
        'require_acknowledgment' => "true",  
        'url' => "https://example.com/abcd" 
        ]);
$envelope_definition->setEventNotification($event_notification1);

**Comment by LarryKlugerDS** [comment]
For more questions like this, please use StackOverflow with tag `docusignapi` Thank you

**Comment by iyyappanpwilco** [comment]
Thank you and one more help needed is that how can i change xml format to json format

**Comment by InbarGazit** [comment]
You can change the Connect format in the Settings page under Integrations->Connect where you set your Connect configuration
