### ISSUE TITLE
finding redirect url expired or not in webhook

### ISSUE THREAD

**Issue by iyyappanpwilco** [docusign/code-examples-php#36]
Hi,
We are using embeded signing and we are are creating redirect url and sent to the user for signing

But can not find  the redirect url is expired or not we found that the redirect url expired time is 120 mins

kindly help us how to find the  redirect url is expired in webhook url

We are using below code for creating redirect url

 $recipient_view_request = $this->clientService->getRecipientViewRequest(
                    $authentication_method,
                    $args['patient_arguments']
                );
                $results = $envelope_api->createRecipientView($args['account_id'], $envelope_id,
                $recipient_view_request);
                  $all_details['patient'] =['envelope_id' => $envelope_id, 'redirect_url' => $results['url']];

**Comment by LarryKlugerDS** [comment]
Hi, Unfortunately I don't quite understand your question.

The **returnUrl** is a **request** attribute that you send **to** DocuSign. See the [documentation](https://developers.docusign.com/docs/esign-rest-api/reference/envelopes/envelopeviews/createrecipient/#schema__recipientviewrequest_returnurl)

After the signing ceremony is done, DocuSign will redirect the user's browser back to your **returnUrl**. 

The URL **for** the signing ceremony is in the response to the getRecipientViewRequest API call. The url **must** be used within 2 minutes. Do not call the getRecipientViewRequest API method until you are ready to redirect the user to the signing ceremony.

**Comment by InbarGazit** [comment]
The URL for signing does expire after 120 seconds like you wrote, so it must be used immediately. the **redirect_uri** is only used after the user signed to redirect them back to you app.
