### ISSUE TITLE
3 Signers with Embedded signing using Docusign

### ISSUE THREAD

**Issue by iyyappanpwilco** [docusign/code-examples-php#37]
Hi,

Can we get three signers sign to docusign using embedded signing
As of now we are using below code
  $signer1 = new Signer([
           'email' => $envelope_args['signer1_email'],'name' => $envelope_args['signer1_name'],
            'role_name' => "d", 'recipient_id' => "1",
            'routing_order' => "0",
            'client_user_id' => ################################
        ]);
         $signer2 = new Signer([
             'email' => $envelope_args['signer2_email'],
             'name' => $envelope_args['signer2_name'],
             'recipient_id' => "1",
             'routing_order' => "0",
             'role_name' => 'p',
            'client_user_id' => @@@@@@@@@@@@@@@@@@@@@@@@@@@
         ]);
 $envelope_definition->setTemplateRoles([$signer1, $signer2
    ]);
       
can we add one more member for signing

**Comment by LarryKlugerDS** [comment]
You can have more than one embedded signer on an envelope. **But only one at a time.**

So your application **must** ensure that only one embedded signing session is active at a time.

(If you have embedded signing session 1, and then open embedded signing session 2, embedded signing session 1 is immediately canceled.)
