### ISSUE TITLE
How to migrate from previous eg-01-php-jwt implementation to this repository?

### ISSUE THREAD

**Issue by akhanukov** [docusign/code-examples-php#38]
Hi, I successfully integrated the repository here (https://github.com/docusign/eg-01-php-jwt) along with the repository (https://github.com/docusign/eg-03-php-auth-code-grant) a few months back. Recently I tried the application and got invalid_grant errors. When I went to research the issue, I see that both repositories have been closed and point to this one. Having tried for days to integrate with the new examples, I can't find any related documents to be able to open a url with data to automatically send an envelop like before. There's also no documentation on migrating from one to another. Can you please help me replace the following:

include_once 'example_base.php';

class SendEnvelope extends ExampleBase {

Where can I find the equivalent code? Thanks!

**Comment by InbarGazit** [comment]
Did you try https://developers.docusign.com/docs/esign-rest-api/quickstart/ ?
this will give you a ZIP file that is pre-configured for your account and you can then use JWT if you want to.

**Comment by akhanukov** [comment]
Yes, that's what I used after trying to use launchers. I can get to the main example page and run all of the examples like on the old eg-03-php-auth-code-grant, however, I had to use eg-01-php-jwt to extend the capability the original time, but now it seems like this is missing from the new code-examples-php repository. For instance, I have no "lib" folder with php files I can run to autorun onload. For instance, here's the list envelop code from the file: eg-01-php-jwt-master/lib/list_envelopes.php:

        include_once 'example_base.php';

        class ListEnvelopes extends ExampleBase {
            public function __construct($client) {
                parent::__construct($client);
            }

            public function listEnvelopes() {
                $this->checkToken();
                $envelopeApi = new DocuSign\eSign\Api\EnvelopesApi(self::$apiClient);



                $options = new DocuSign\eSign\Api\EnvelopesApi\ListStatusChangesOptions();
                $date = new Datetime();
                $date->sub(new DateInterval("P30D"));
                $options->setFromDate($date->format("Y/m/d"));
                return $envelopeApi->listStatusChanges(self::$accountID, $options);
            }
        }


Is there similar examples using the new JWT auth flow?

**Comment by akhanukov** [comment]
Here is the original zip I used. But I'm not able to find equivalent classes nor code to make it work with the new example code like I was able to using this. Please note the send_envelopes.php. That is how my application runs. I need to figure out how to do this with the new repository please. Thanks for all of your help!

[eg-01-php-jwt-master.zip](https://github.com/docusign/code-examples-php/files/6926617/eg-01-php-jwt-master.zip)

**Comment by akhanukov** [comment]
I see bits and pieces that were extracted from this repository and made more modular for use across multiple APIs. The problem is, I doubt its as easy as swapping out some include calls. Any help is greatly appreciated.

**Comment by AaronWDS** [comment]
The sendEnvelopes.php example in the old repository is now [example 2](https://github.com/docusign/code-examples-php/blob/master/src/Controllers/Examples/eSignature/EG002SigningViaEmail.php) in the launcher. JWT is handled [here](https://github.com/docusign/code-examples-php/blob/master/src/Services/JWTService.php). `invalid_grant` errors have happened for me when I didn't set the correct base path or had a missing variable not filled in like the impersonation user id. You'll run the quickstart, then you can login using JWT and run the example 2 which would have the same functionality as before.

**Comment by InbarGazit** [comment]
We created a new JWT project and you can use the DocuSign [Quickstart](https://developers.docusign.com/docs/esign-rest-api/quickstart/) to get it downloaded and automatically configured for your needs.
