### ISSUE TITLE
Multiple signers in part-11 module with in single document

### ISSUE THREAD

**Issue by iyyappanpwilco** [docusign/code-examples-php#41]
How can we implement multiple signers  with in same document using template id after enabling part-11 module

**Comment by InbarGazit** [comment]
Great question. I suggest you first try to do this from the web app, without PHP or API. Create a template that does what you need, using an account that has part-11 (do you have one already?)
You can add the recipients, add their tabs (tags/signing elements) and make sure the template works exactly as you expect.
Only then I would start thinking about coding and API etc. 
I can show you the examples that you can use once you have the template working as you wish.

**Comment by InbarGazit** [comment]
Part-11 requirements are not relevant to the code examples in here. You can compete this using either the eSignature API or the web app.
