### ISSUE TITLE
Sending Email to users not signed in the document

### ISSUE THREAD

**Issue by iyyappanpwilco** [docusign/code-examples-php#43]
Hi ,

Kindly let us know the code in php for the scenario

We have  2 signers using the template id for signing and one user is signed and other is not signd

We need to send email to user who is not signed the document

**Comment by InbarGazit** [comment]
Emails will be sent automatically to the next signer if they are set to be "remote signer". "Embedded Signers" do not get emails. You should check that your signer doesn't have a `clientUserId` associated with the object, as that indicates embedded signer.

**Comment by InbarGazit** [comment]
This is something you can do using DocuSign eSignature. I'm closing this issue as no action is needed at this time on our part.
