### ISSUE TITLE
Envelope Creation Error

### ISSUE THREAD

**Issue by iyyappanpwilco** [docusign/code-examples-php#44]
Hi We are getting Error on Envelope Creation
We are getting Error as "USER_AUTHENTICATION_FAILED","message":"One or both of Username and Password are invalid. Invalid access token"
Kindly let us know  changes to fix the issue

**Comment by InbarGazit** [comment]
Are you using JWT or Auth Code Grant? how do you get an access token?

**Comment by InbarGazit** [comment]
This error indicated wrong token was used for authentication. It's possible the token was expired. I would suggest to use the [quickstart](https://developers.docusign.com/docs/esign-rest-api/quickstart/) to ensure all configuration was set correctly to be able to obtain tokens.
