### ISSUE TITLE
API Example code should not reference the Quickstart app

### ISSUE THREAD

**Issue by dburleson** [docusign/code-examples-php#47]
Firstly, this may come across as opinion or personal taste. Please see it as feedback on how to improve the usability and ease of integration of the API in existing web apps.

The API documentation often references code from the quick start app. While this is fine for new applications, reference the quick start app's code introduces barriers for anyone trying to integrate DocuSign's API into an existing application that possibly doesn't adhere to the quickstart app's code structure and methodology. Therefore, this requires existing app developers to untangle the quickstart app's code to find the core of the DocuSign API's usage. 

A suggestion on API documentation, let the calls and processes code be minimal and only for the purpose of demonstrating how to make or use the call without any additional code which isn't necessary for the demonstration. On this page (https://developers.docusign.com/docs/esign-rest-api/sdk-tools/php/auth/), the code examples display a snippet of the quickstart code and a link to it to Github. But, the dev must then dive through controllers and interfaces before actually getting to the code that uses DocuSign's API. This is an example of the quickstart application's code getting in the way of the API's documentation.

A good example of API documentation and examples, in my opinion, is Stripe: https://stripe.com/docs/api?lang=php . It displays simplistic, stand-alone code snippets demonstrating all the different methods with an explanation of what it's used for, response, and parameters.

**Comment by bendowlingds** [comment]
Hi @dburleson, Thanks for your feedback. This is something that I will certainly pass on to the documentation team for review.

**Comment by dburleson** [comment]
thank you for the quick responses and for taking on board my comments.

**Comment by InbarGazit** [comment]
@dburleson in response to your (And others) we released minimal code examples that can be packaged and configurated automatically using quickstart. These two new options allow you to choose with JWT or Auth Code Grant and get a single code example with a package that include less than 10 files. These are available for all our languages including PHP.
