### ISSUE TITLE
Error: Connection refused for URI

### ISSUE THREAD

**Issue by Ben-CA** [docusign/code-examples-php#57]
I'm new to the DocuSign API. Trying the sample code, I have it running on my localhost, and when I try to authenticate:

![image](https://user-images.githubusercontent.com/47060874/179543155-fdec01eb-8045-4c99-ac11-0df56eec5799.png)

![image](https://user-images.githubusercontent.com/47060874/179543502-98368ae0-ccf2-477d-8a99-ad636538ea06.png)

And then the callback gives me a 500 error:
![image](https://user-images.githubusercontent.com/47060874/179543584-bcc72c59-ae28-4962-871a-743261ac6e84.png)

When I check my PHP server logs, I get this:

Next GuzzleHttp\Exception\ConnectException: Connection refused for URI https://account-d.docusign.com/oauth/token in C:\MAMP\htdocs\docusign\vendor\guzzlehttp\guzzle\src\Handler\StreamHandler.php:72

Has anyone encountered the same thing? Or any ideas?

**Comment by AbdulrahmanGameel** [comment]
This is the expected behavior, you only really care about the code that's being passed back and as you can see it's passed successfully in the URL that you're getting.
<img width="1787" alt="image" src="https://user-images.githubusercontent.com/32441590/179744896-0e87f3b4-f6d0-41c9-b109-ee3e4e8a95e9.png">

**Comment by Ben-CA** [comment]
The expected behavior is a 500 error? What do I do with that code? I'm not seeing anything in the Readme about that. I thought the sample code would have methods to use the API with the included demo_documents - not just provide an authorization token which you could use Postman to do...

**Comment by InbarGazit** [comment]
Did you run this from quickstart?

**Comment by InbarGazit** [comment]
No, this 500 error is not expected for the PHP code if it's configured and run correctly

**Comment by Ben-CA** [comment]
> Did you run this from quickstart?

Yes, I downloaded the source with my credentials included via **https://developers.docusign.com/docs/esign-rest-api/quickstart/**

**Comment by Ben-CA** [comment]
Found this in the error logs as well:
[19-Jul-2022 17:30:09 UTC] PHP Fatal error:  Uncaught GuzzleHttp\Exception\RequestException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://account-d.docusign.com/oauth/token in C:\MAMP\htdocs\docusign\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:211
Stack trace:

_From the CURL docs:_
**CURLE_PEER_FAILED_VERIFICATION (60)**
The remote server's SSL certificate or SSH md5 fingerprint was deemed not OK. This error code has been unified with CURLE_SSL_CACERT since 7.62.0. Its previous value was 51.

I'm not sure if this is an issue with my localhost config, or an issue with DocuSign's certificate...

**Comment by Ben-CA** [comment]
Must have just been an issue with my localhost config. I tried using a Docker, and that worked.

![image](https://user-images.githubusercontent.com/47060874/179815442-938ba381-8a10-4071-aaef-c0976a5cd31b.png)
