### ISSUE TITLE
Example does not work out of the box: wrong API calls

### ISSUE THREAD

**Issue by mariobig** [docusign/code-examples-php#6]
There are plenty of errors in the published code.
For example:

everywhere: 
$envelope_api = new \DocuSign\eSign\Api\EnvelopesApi($api_client);

should be:
 $envelope_api = new \DocuSign\eSign\Client\Api\EnvelopesApi($api_client);

**Comment by InbarGazit** [comment]
@mariobig  can you tell me which version of the SDK and the API you are using?

**Comment by mariobig** [comment]
Hi ,

I followed step by step installation instruction published  at https://github.com/docusign/eg-03-php-auth-code-grant.

Mario

**Comment by InbarGazit** [comment]
I understand, but can you still try to find the versions and let us know?

**Comment by mariobig** [comment]
In my opinion it has nothing to do with versions of SDK or API. Official DocuSign SDK is correct and up to date.

Simply, the code itself published here in examples contains a lot of bugs:

Examples:
src/EG001EmbeddedSigning.php
line 109: $api_client = new \DocuSign\eSign\ApiClient($config);
should be: $api_client = new \DocuSign\eSign\Client\ApiClient($config);


src/EG002SigningViaEmail.php
line 109: $api_client = new \DocuSign\eSign\ApiClient($config);
should be: $api_client = new \DocuSign\eSign\Client\ApiClient($config);


src/EG008CreateTemplate.php
line 94: $api_client = new \DocuSign\eSign\ApiClient($config);
should be: $api_client = new \DocuSign\eSign\Client\ApiClient($config);


src/EG003ListEnvelopes.php:	does not work
src/EG006ListEnvelopes.php:	does not work
src/EG007ListEnvelopes.php:	does not work (same bug like in EG001EmbeddedSigning.php and src/EG002SigningViaEmail.php)
src/EG009ListEnvelopes.php:	does not work beacuse example 8 does not return template ID
src/EG016ListEnvelopes.php:	does not work (line 112 same bug like in EG001EmbeddedSigning.php and src/EG002SigningViaEmail.php)
src/EG018ListEnvelopes.php:	does not work (same bug like in EG001EmbeddedSigning.php and src/EG002SigningViaEmail.php and others bugs as well)
src/EG019ListEnvelopes.php:	does not work (error in eg-03-php-auth/vendor/twig/twig/src/Loader/FilesystemLoader.php on line 250)

**Comment by LarryKlugerDS** [comment]
Thank you @mariobig for the bug report. You're correct, the example should work properly out of the box.

I have filed bug DEVDOCS-1710

**Comment by AaronWDS** [comment]
Confirmed fixed, closed.

 https://github.com/docusign/eg-03-php-auth-code-grant/blob/master/src/Services/ClientService.php#L11
