### ISSUE TITLE
QuickStart cannot authenticate with  JWT login

### ISSUE THREAD

**Issue by aingelc12ell** [docusign/code-examples-php#66]
I have downloaded the QuickStart example and set the configs.

What am I missing?

I am able to authenticate using ACG, but not JWT.

Here the error
```
PHP Fatal error:  Uncaught Error: Call to a member function getAccessToken() on null in /sources/docusign/src/Services/JWTService.php:52
Stack trace:
#0 /sources/docusign/src/Services/RouterService.php(391): Example\\Services\\JWTService->login()
#1 /sources/docusign/src/Services/RouterService.php(275): Example\\Services\\RouterService->ds_login()
#2 /sources/docusign/public/index.php(42): Example\\Services\\RouterService->router()
#3 {main}
 thrown in /sources/docusign/src/Services/JWTService.php on line 52, 
referer: http://localhost/docusign/index.php?page=must_authenticate
```

**Comment by sb1994** [comment]
Hi,

I am with the Developer Support team in DocuSign

What scopes are you using to get consent in the application? 

Have you tried to follow the steps in the following article to make sure that you are getting your JWT token
https://developers.docusign.com/platform/auth/jwt/jwt-get-token/

**Comment by aingelc12ell** [comment]
I am working straight out of the QuickStart.  Do I need to get a JWT token?

I tried to follow the link you provided and it leads me to the same error I pointed above.

**Comment by AaronWDS** [comment]
we did run into a prior issue with 1st run on JWT when running quickstart. That problem has since been remedied and is related to the changes found here: https://github.com/docusign/code-examples-php/blob/master/src/Services/RouterService.php#L196 Update your RouterService.php file to match this updated copy and your issue should be resolved. Let me know if this helps.

**Comment by aingelc12ell** [comment]
This do solved my issues magically. Great Thanks!
Wouldn't this be pushed to master?

**Comment by InbarGazit** [comment]
@aingelc12ell this is in the master branch already
